### PR TITLE
Altered registration template to have year 'drop down' option

### PR DESCRIPTION
**Pull request by cmarshall97**
So I was testing everything out and came up with the below.... 
1) Register.html-Only flashed messages for first and last name populate at top of the page . For some reason the other messages  from the user.py file under Models don't populate on the screen. I am going to look more into this tomorrow. 
2) With this, I am curious to know if lines 92-94 in (Models - user.py) will have to be adjusted since the input for 'year' is now a drop down menu instead of a text input.
3) Also I tried to register a user with a password that didn't match and it still registered them.... so again, there is something my Jinja is not grabbing on the register page.
4) Once I am able to see all the validations I was going to add a red color to the validations and try to place them underneath each input. (Not sure how to do tis just yet but going to try)
5) I  got an error page when trying to crate a new project.. so with this, I am not sure what the dashboard looks like when projects start getting added.

If anyone knows an easy fix to any of these, by all means have at it! I will be back around 8:00pm tomorrow to tackle them.

### CODE REVIEW

**Review by Teknicl — APPROVED** [review]
👍

**Comment by Teknicl** [comment]
> 1. Register.html-Only flashed messages for first and last name populate at top of the page . For some reason the other messages  from the user.py file under Models don't populate on the screen. I am going to look more into this tomorrow.

I was able to see all flash messages but the year.

> 2. With this, I am curious to know if lines 92-94 in (Models - user.py) will have to be adjusted since the input for 'year' is now a drop down menu instead of a text input.

I see a few options here and should coordinate the decision with @Lopez-CL as the Project form also has drop-downs.

- I can add validation logic if you can default the drop-down on a header like "choose a year".  Without that there is no unique condition I can think of.
- I can remove validation logic if there are only valid options to choose from.  Presently for Register this is the case but not for Project form.

> 3. Also I tried to register a user with a password that didn't match and it still registered them.... so again, there is something my Jinja is not grabbing on the register page.

Oops I forgot to fixed this just now.  I tested and it's still broken.  I will fix later today unless someone else want to take a stab at it.

> 5. I  got an error page when trying to crate a new project.. so with this, I am not sure what the dashboard looks like when projects start getting added.

I was able to resolve that with my latest merge.

**Comment by Lopez-CL** [comment]
Jus letting everyone know that I've seen these comments. Thanks @cmarshall97 for noting what you plan to work on. 

In terms of your 4. problem, I think I know how you could do it, but my solution creates more jinja in the html, but let me know if you want to chat about this.

**Comment by cmarshall97** [comment]
Thanks for your comments guys! I'm just looking over these before I head to the fields. Ill be back around 8:15 EST to keep working on this.
Torrei -Thanks for your input. If there is something on my end you see that needs fixing let me know. I'm also super glad you were able to see the flash messages on your end (I was low-key stressing today at work trying to figure out why it wasn't working). I'm hoping when I come back it will also show on my end. 
Chris - Yes, if you have an idea I would definitely be up for a call or chat about how to make it work when I get back. 
Adam- Thanks for getting me going last night! That was a huge help!

*I haven't touched any of the files since my push last night so if someone needs to go in and do something go ahead.

Thank you for all your input!

**Pull request merged**
